before:
  hooks:
    - go mod tidy
builds:
  - main: ./lfr
    id: "lfr"
    binary: lfr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
        - -w -s
        - -X github.com/lgdd/liferay-cli/lfr/pkg/cmd/version.number={{.Version}}
        - -X github.com/lgdd/liferay-cli/lfr/pkg/cmd/version.commit={{.Commit}}
        - -X github.com/lgdd/liferay-cli/lfr/pkg/cmd/version.date={{.Date}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
