project_name: "lfr-cli"
before:
  hooks:
    - go mod tidy
release:
  mode: keep-existing
builds:
  - id: "lfr-cli"
    binary: lfr
    main: ./lfr
    ldflags:
      - -w -s
      - -X github.com/lgdd/lfr-cli/lfr/pkg/cmd/version.Number={{.Version}}
      - -X github.com/lgdd/lfr-cli/lfr/pkg/cmd/version.Commit={{.Commit}}
      - -X github.com/lgdd/lfr-cli/lfr/pkg/cmd/version.Date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
archives:
  - format_overrides:
      - goos: windows
        format: zip
nfpms:
  - description: LFR is an unofficial tool written in Go that helps you create & manage your Liferay projects.
    homepage: https://github.com/lgdd/lfr-cli
    license: MIT
    maintainer: Louis-Guillaume Durand <louis-guillaume.durand@liferay.com>
    formats:
      - deb
      - rpm
      - apk
brews:
  - repository:
      owner: lgdd
      name: homebrew-tap
      token: "{{ .Env.LFR_CLI_GH_TOKEN }}"
    directory: Formula
    homepage: https://github.com/lgdd/lfr-cli
    description: LFR is an unofficial tool written in Go that helps you create & manage your Liferay projects.
    install: |
      bin.install "lfr"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
