version: 2

project_name: "lfr-cli"
before:
  hooks:
    - go mod tidy
release:
  mode: keep-existing
builds:
  - id: "lfr-cli"
    binary: lfr
    main: ./cmd/lfr
    ldflags:
      - -w -s
      - -X github.com/lgdd/lfr-cli/internal/cmd/version.Number={{.Version}}
      - -X github.com/lgdd/lfr-cli/internal/cmd/version.Commit={{.Commit}}
      - -X github.com/lgdd/lfr-cli/internal/cmd/version.Date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
archives:
  - format_overrides:
      - goos: windows
        formats: [zip]
nfpms:
  - description: LFR is an unofficial tool written in Go that helps you create & manage your Liferay projects.
    homepage: https://github.com/lgdd/lfr-cli
    license: MIT
    maintainer: Louis-Guillaume Durand <louis-guillaume.durand@liferay.com>
    formats:
      - deb
      - rpm
      - apk
homebrew_casks:
  - name: lfr-cli
    binaries:
      - lfr
    repository:
      owner: lgdd
      name: homebrew-tap
      token: "{{ .Env.LFR_CLI_GH_TOKEN }}"
    directory: Casks
    homepage: https://github.com/lgdd/lfr-cli
    description: LFR is an unofficial tool written in Go that helps you create & manage your Liferay projects.
winget:
  - name: lfr-cli
    publisher: lgdd
    publisher_url: https://github.com/lgdd
    publisher_support_url: https://github.com/lgdd/lfr-cli/issues
    homepage: https://github.com/lgdd/lfr-cli
    short_description: Unofficial CLI to create & manage Liferay projects.
    description: LFR is an unofficial tool written in Go that helps you create & manage your Liferay projects.
    license: MIT
    license_url: https://github.com/lgdd/lfr-cli/blob/main/LICENSE
    repository:
      owner: lgdd
      name: winget-pkgs
      token: "{{ .Env.LFR_CLI_GH_TOKEN }}"
      pull_request:
        enabled: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
