name: auto-update-assets

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  builder:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update Client Extensions Samples
        working-directory: ./lfr/pkg/assets/tpl/cx/liferay-portal
        run: |
          mv git .git
          git pull
          mv .git git
      - name: Commit Client Extensions Changes
        run: |
          git config --global user.name 'lgdd'
          git config --global user.email 'lgdd@users.noreply.github.com'
          git add ./lfr/pkg/assets/tpl/cx/
          git commit -am "chore: auto update client extensions samples" || echo "We're good for now. See you next time!"
          git push
