name: auto-update-assets

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 0 * * *'

jobs:
  builder:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update Client Extensions Samples
        working-directory: ./lfr/pkg/assets/tpl/cx/liferay-portal
        run: |
          mv git .git
          git pull
          git reflog expire --expire=now --all
          git gc --aggressive --prune=all
          mv .git git
      - name: Commit Client Extensions Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add ./lfr/pkg/assets/tpl/cx/
          git commit -am "chore: auto update client extensions samples" || echo "We're good for now. See you next time!"
          git push
