name: Release

on:
  push:
    tags:
      - "v*"
      - "!*-alpha*"
      - "!*-beta*"
      - "!*-rc*"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GH_API_TOKEN: "${{ secrets.GH_API_TOKEN }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Check GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser
        if: ${{ success() }}
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
